### ISSUE TITLE
Final Plugin Release Checklist

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#32]
In theory everything that needs to be done before final release. Might be updated as development progresses.

## GENERAL 
- [x] Darken the icons of the tabs you cannot use currently (when no map is selected)
- [x] Add notices telling you to set HTTP enabled to true for studio if it is disabled
- [x] Add automatic detection for whether or not the special folder is created or destroyed when editing a map
- [x] If no map gets auto selected, then set the current tab to the toolbox tab
- [x] Fix appearance of message UI
- [x] Update colorwheel to start with current color + update Value slider hue
- [x] Popup when an addon gets inserted
- [x] Neaten up codebase (e.g. code casing, misused computed, indents, etc.)
- [x] Ensure codebase is as strictly typed as possible
- [x] Make sure all elements respect themes (even when changed)
- [x] Make plugin not work unless in Edit mode
- [x] Preload all images when plugin loads 
- [x] Make sure all code is dependency-managed (i.e. `:get()` runs with false when needed) to make Fusion v0.3 conversion easier.
- [x] Make sure all code functions when specific folders aren't added

## AUDIO LIBRARY 
 - [x] Change refresh period to when the player leaves the tab instead of when they focus it
 - [x] Debounce of 2 minutes per API refresh.
 - [x] Debate if volume slider should exist and fix a bug where it's hidden
 - [x] Edit color appearance of the page turns
 - [x] Change the about tab to a text dropdown, along with some formatting.
 - [x] Add a "how to submit audios" dropdown below
 - [x] Add search bar
 - [x] Fix slider behavior to work when mouse is not over the slider frame (this also means some sliders don't reach their full value)
 - [x] Fix plugin frame size messing with the size of the audio tab thingys (dynamic page sizes should fix this)
 - [x] Audio label adjustments:
     - [x] Shrink Y size 
     - [x] Adjust name
     - [x] Adjust play button
     - [x] Duration length bar
     - [x] Set map BGM button change
- [x] Possibly add a textbox for automatically going to a page instead of clicking the scroll buttons
- [x] Add dynamic page cycle button colors
- [x] Universe ID not being reset causing studio testing to completely break
- [x] Add now playing bar for songs
- [x] Detect sound loading and fix freeze bug.
- [x] Rewrite

## OBJECT TAGS TAB
- [x] Redo formatting of the metadata tooltips
 
## TOOLBOX TAB
- [x] Fix gap in map component labels
- [x] Integrate EasyTP
	- [x] Integrate with ObjectTags
- [x] Integrate Waterjets
	- [x] Integrate with ObjectTags
- [x] Fix bad scaling with TRIA.os map kit image
- [x] Add mini "select map to continue" displays for components and addons

## PUBLISH TAB
- [x] Adjust the colors and border thicknesses of the main frames
- [x] Slightly adjust the look of the TRIA map creator key
- [x] Fix inconsistency with the 3 different main text labels
- [x] Disabled overlay

## SCRIPTING TAB
- [x] Possibly add a quick open for Roblox creator docs for API reference
- [x] Stress test tab functionality
- [x] Add support for that one last part that doesnt exist yet
- [x] Make UI consistent to publish UI changes

## DEBUG VIEW MODES
- [x] Optimize further
    - [x] Ability to set part visuals and update them based on listening to SpecialFolder children
    - [x] Appearance & customizable appearance for each object type
    - [x] UI & abillity to toggle on and off for main categories and per object type
 - [x] Abillity for debug view to dynamically create to each variant made
 - [x] Integrate Waterjets & EasyTP

-----

# FINAL
 - [x] Final testing
 - [x] Manually convert the existing audio library
 - [x] Make sure all code is as optimised as possible (confirm this with the debug menu)

**Comment by KryptonForce102** [comment]
> Debounce of 2 minutes per API refresh.

iirc this already exists

> Possibly add a quick open for Roblox creator docs for API reference

F1 does this the last time I checked.
