### ISSUE TITLE
Update plugin for 1.0

### ISSUE THREAD

**Issue by grif-0** [Tria-Studio/Tria-OS-Plugin#37]
```[tasklist]
### Tasks
- [ ] Remove map manager page
- [ ] Orb projections
- [ ] Add terrain stuff to save terrain to your map
- [ ] Add studio keybind support
```
